
POST http://localhost:8080/api/
Content-Type: application/json

{
    "name": "alternative"
}



###

DELETE http://localhost:8081/api/genres/11500124-8411-469c-8ffc-5dce0757608b


###
GET http://localhost:8080/api/genres


