server {
    listen 80; 

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    
    location /api/genres {
        proxy_pass http://categories-app:8080; 
    }

    
    location /api/songs {
        proxy_pass http://elements-app:8080;
    }
}